#!/bin/bash

# Requires: mullvad (cli) and nftables


set -euo pipefail

SCRIPT_DIR=$HOME/LINUX/VPN

# List of countr codes to exclude from connection
# If you don't want to exclude any CC set it to '(0)'
# If you want to add more, just follow the pattern.
EXCLUDE_COUNTRY_CODES='(us|ca|jp|au|hk|gb)'

mullvad relay update
MULLVAD_RELAYS=( $(mullvad relay list | grep 'wireguard' | awk '{ print $1 }' | grep -Ev $EXCLUDE_COUNTRY_CODES) )

# Pick a random country code.
size=${#MULLVAD_RELAYS[@]}
index=$(($RANDOM % $size))
relay=${MULLVAD_RELAYS[$index]}

usage() {
    echo "usage:"
    echo "  $(basename "$0") up"
    # echo "  $(basename "$0") upc <2-char country code>"
    echo "  $(basename "$0") down"
    exit 1
}

if [ $# -lt 1 ]; then
    usage
fi

case "$1" in
    "upc")
        if [ $# -ne 2 ]; then
            usage
        fi

        echo "NOT IMPLEMENTED..."
        ;;

    "down")
        mullvad disconnect
        sudo nft delete table inet mullvad-ts
        ;;

    "up")
        sudo tailscale down

        echo "Applying ntf rules..."
        sudo nft -f $SCRIPT_DIR/mullvad.rules

        echo "Connecting to server $relay..."
        mullvad relay set hostname $relay
        mullvad connect -w
        mullvad dns set default

        echo "Connecting to tailscale..."
        sudo tailscale up
    ;;

    *)
        usage
esac

