#!/bin/bash

# Requires: mullvad (cli), nftables and tailscale

# ---------------------------
# CONFIG VARIABLES YOU SHOULD CHANGE
RULES_DIR=$HOME/LINUX/VPN # Path to where mullvad.rules file is located
EXCLUDE_COUNTRY_CODES='(us|ca|jp|au|hk|gb)' # Country codes to avoid
# ----------------------------

DNS='default'

usage() {
    echo "usage:"
    echo "  $(basename "$0") conf - Configure nftables so Mullvad and Tailscale can work. (use -h for more info)"
    echo "  $(basename "$0") up  - Connect to Mullvad and Tailscale and configure nftables. (use -h for more info)"
    #echo "  $(basename "$0") upc <2-char country code>"
    echo "  $(basename "$0") down - Disconnect from Mullvad only, or Mullvad and Tailscale if -a option enabled. (use -h for more info)"
    exit 0
}

upusage() {
    echo "Apply nftables configuration and connect to Mullvad and Tailscale."
    echo "usage: "
    echo "mtc up [-OPTIONS]:"
    echo "  -r: No-disk/RAM only Mullvad relays (default: all servers)"
    echo "  -d: Set custom Mullvad DNS Server"
    echo "  -h: Show this help message."
    exit 0
}

downusage() {
    echo "Bring down Mullvad and remove nftables configuration."
    echo "usage: "
    echo "mtc down [-OPTIONS]:"
    echo "  -a: Stop Mullvad and Tailscale (default: only stop Mullvad)"
    echo "  -h: Show this help message."
    exit 0
}

confusage() {
    echo "Apply nftables configuration so Mullvad and Tailscale can work together and do nothing more."
    echo "usage: "
    echo "mtc conf [-OPTIONS]:"
    echo "  -d: Remove the nftables configuration."
    echo "  -h: Show this help message."
    exit 0
}

if [ $# -lt 1 ]; then
    usage
fi

case "$1" in
    "upc")
        if [ $# -ne 2 ]; then
            usage
        fi

        echo "NOT IMPLEMENTED..."
        ;;

    "conf")
        OPTIND=2   
        while getopts ":d :h" opt; do
            case $opt in
                d) 
                    echo "[INFO] Removing nftables rules..."
                    sudo nft delete table inet mullvad-ts
                    exit 0
                    ;;
                h) 
                    confusage 
                    exit 0
                    ;;
                \?) 
                    echo "[ERROR] WRONG OPTION"
                    echo ""
                    confusage
                    exit 1
                    ;;
            esac
        done
        echo "[INFO] Applying nftables rules..."
        sudo nft -f $RULES_DIR/mullvad.rules
    ;;

    "down")
        OPTIND=2   
        while getopts ":a :h" opt; do
            case $opt in
                a) sudo tailscale down ;;
                h) downusage ;;
                \?) 
                    echo "[ERROR] WRONG OPTION"
                    echo ""
                    downusage
                    exit 1
                    ;;
            esac
        done

        mullvad disconnect
        sudo nft delete table inet mullvad-ts
        ;;

    "up")
        ram=false      
        OPTIND=2
        while getopts ":r :h :d:" opt; do
            case $opt in
                r) ram=true ;;
                d) DNS=$OPTARG ;;
                h) upusage ;;
                \?) 
                    echo "[ERROR] WRONG OPTION"
                    echo ""
                    upusage
                    exit 1
                ;;
            esac
        done
        
        bash $0 down -a || echo "Ignoring error..."
        mullvad relay update
        if [ $ram = true ] ; then
            MULLVAD_RELAYS=( $(mullvad relay list | grep -E '(wg)' | awk '{ print $1 }' | grep -Ev $EXCLUDE_COUNTRY_CODES) )
        else
            MULLVAD_RELAYS=( $(mullvad relay list | grep -E '(wireguard|wg)' | awk '{ print $1 }' | grep -Ev $EXCLUDE_COUNTRY_CODES) )
        fi

        # Pick a random country code.
        size=${#MULLVAD_RELAYS[@]}
        index=$(($RANDOM % $size))
        relay=${MULLVAD_RELAYS[$index]}   
        sudo tailscale down

        echo "[INFO] Restarting tailscale connection..."
        sudo tailscale down
        sudo tailscale up

        echo "[INFO] Applying nft rules..."
        sudo nft -f $RULES_DIR/mullvad.rules

        echo "[INFO] Connecting to server $relay..."
        echo "[INFO] Setting up Mullvad DNS to $DNS..."
        if [ $DNS = "default" ] ; then
            mullvad dns set default
        else
            mullvad dns set custom $DNS
        fi
        mullvad relay set hostname $relay
        mullvad connect -w
        mullvad disconnect
        mullvad connect -w
    ;;

    *)
        usage
esac
